export const SET_CURRENT_WEATHER_DATA = 'SET_CURRENT_WEATHER_DATA';
export const SET_DAILY_WEATHER_DATA = 'SET_DAILY_WEATHER_DATA';
export const SET_HOURLY_WEATHER_DATA = 'SET_HOURLY_WEATHER_DATA';

export const TOGGLE_CURRENT_WEATHER_FETCHING = 'TOGGLE_CURRENT_WEATHER_FETCHING';
export const TOGGLE_DAILY_WEATHER_FETCHING = 'TOGGLE_DAILY_WEATHER_FETCHING';
export const TOGGLE_HOURLY_WEATHER_FETCHING = 'TOGGLE_HOURLY_WEATHER_FETCHING';

export const REQUEST_ERROR = 'REQUEST_ERROR';
